POP_SIZE: 200
NEIGHBORHOOD_SIZE: 3
NUM_SENSORS: 700
NUM_SINK_NODES: 1
NUM_GENERATION: 5000
DIMENSIONS:
  LENGTH: 1000
  WIDTH: 50
DISTRIBUTION: 'gauss'
OPERATORS:
  CROSSOVER RATE: 0.9
  MUTATION RATE: 0.5
